### ISSUE TITLE
Validating parameters and printing to console

### ISSUE THREAD

**Issue by davidverweij** [davidverweij/csv2docx#26]
## Validating Parameters

A quick test run with false arguments currently throws an exception. After setting up unit testing, we should handle these gracefully. For example, we could use a similar approach with `pathlib` used in the creation of a file, to check if the `data.csv` and `template.docx` exists before proceeding to read from it. 

## Printing to console

Even though we separated the CLI and the module here #15, we have print statements in the main module. Instead, I'd argue we should throw Errors and handle these in the `cli.py`. This way anyone using the module can expect a result or specific error, and handle these themselves.

## Next Steps

Low priority at the moment, but I'd argue to further separate CLI and logic by throwing pre-defined errors and handling these in the use of the module (be it in `cli.py` or any other use of the package).

Thoughts?

**Comment by salmannotkhan** [comment]
We can write those validation into main function so it'll check for validation before using covert() function

**Comment by jawrainey** [comment]
### Validation

I agree that we should validate parameters inside `convert` and maybe create a utils file to abstract the types of validation we need to do, e.g. checking if files exists, etc. Using`try/catch/throws` to raise issues upstream would be help from the library side and if we integrate logging for raising exceptions to click (more details below) then we can keep the CLI code as it is. 

### Printing to console

Printing to console inside the library is an issue as it is quite unusual behaviour for a library to output information as it's running or loading CSVs. Also, our current use of [`exit()`](https://github.com/davidverweij/csv2docx/blob/master/csv2docx/csv2docx.py#L44) will kill the python programme. Maybe we should consider adding a [_logging_](https://docs.python.org/3/library/logging.html) (see also [debug mode](https://docs.python.org/3/library/logging.html#logging.Logger.debug)) that can be enabled/disabled in `debug mode` instead of printing? I see that [click log](https://click-log.readthedocs.io/en/stable/) exists (although the package has not been updated in 3 years). 

### Next Steps

We should investigate how other libraries that have CLIs approach this problem.

**Comment by davidverweij** [comment]
Just putting it here so we don't forget - the code currently doesn't ignore capitalisation. In other words: if the `.csv` header is "Name", but the `.docx` merge field is "NAME" it will fail. Potentially worth setting the default to case insensitive?

**Comment by davidverweij** [comment]
PR #34 removes prints to the console from the module, instead throws errors or warnings - that are caught in the CLI. If succesfull PR - I suggest to close this issue.
