### ISSUE TITLE
Doulbe-check Python 2.7 dependency for MacOS and docx-mailmerge's lxml dependency

### ISSUE THREAD

**Issue by davidverweij** [davidverweij/csv2docx#6]
This project started with the need for a MacPort of the lxml dependency, though we have now upgraded to Python 3.8. I need to test whether this dependency is still there, and how to incorporate this in the poetry install.

**Comment by davidverweij** [comment]
See [this](https://stackoverflow.com/questions/10666578/how-do-i-install-lxml-on-mac-os-x-10-7-4-i-have-exhausted-all-options) related StackOverflow Question

**Comment by davidverweij** [comment]
I uninstalled the MacPort of lxml (py27-lxml) (see https://lxml.de/installation.html) and the code still runs. I am assuming it operates on one of the more updated lxml packages. Closing this issue, unless @jawrainey has other insights.

**Comment by jawrainey** [comment]
> @jawrainey is this due to the dependency in poetry.lock, or a subdependency in docx-mailmerge?

Yes, and I think the issue you had was likely due to incompatible versions between packages or some weird setup, which is typical and further motivates our use of poetry 👍 

For reference, `docx-mailmerge` depends on lxml as you noted above. Poetry: (i) assigns [lxml as a subdepdency](https://github.com/davidverweij/csv2docx/blob/master/poetry.lock#L17-L18); and (ii) chooses the highest version to use based on `docx-mailmerge` version (i.e. [4.5](https://github.com/davidverweij/csv2docx/blob/master/poetry.lock#L20-L26)). 

Interestingly, poetry by default will add all platform versions of a subdepdency to its lock file (i.e. [OSX/Windows/Linux](https://github.com/davidverweij/csv2docx/blob/master/poetry.lock#L47-L75)), which makes me confident that our move to poetry will make running `csv2docx` a success on windows. I've verified that `csv2docx` works on `Ubuntu 18.04` with python `3.8.2` 👍
